name: Create GitHub Milestone

on:
  workflow_dispatch:  # Allows for manual triggering

jobs:
  create_milestone:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create GitHub milestone
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Use the PAT here
        run: |
          response=$(curl -X POST https://api.github.com/repos/dheenapm/testapproval/milestones \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -d '{
              "title": "New Milestone",
              "description": "This is a description of the milestone.",
              "due_on": "2024-12-31T23:59:59Z"
            }')
          
          # Check if the milestone creation was successful
          if echo "$response" | grep -q "id"; then
            echo "Milestone created successfully."
          else
            echo "Error creating milestone. Response: $response"
            exit 1
          fi
